workflows:
  android-debug-workflow:
    name: Android Debug Build
    max_build_duration: 15
    environment:
      java: 17
      android_sdk: latest
    scripts:
      - name: Generate Gradle Wrapper
        script: gradle wrapper --gradle-version 8.5
      - name: Grant execute permission for gradlew
        script: chmod +x gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
